packages:
  - examples/*
  - packages/*

catalog:
  "@types/react": ^19.1.15
  "@types/react-dom": ^19.1.9
  "@vitejs/plugin-react": ^5.0.4
  "@vitejs/plugin-vue": ^6.0.1
  react: ^19.1.1
  react-dom: ^19.1.1
  tsup: ^8.5.0
  typescript: ^5.9.2
  vite: ^7.1.7
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-dts: ^4.5.4
  vite-plugin-dynamic-importmap: ^2.0.3
  vue: ^3.5.22
  vue-tsc: ^3.1.0
